# Generated by Django 5.1.1 on 2024-09-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, max_length=60, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, db_index=True, verbose_name='Описание')),
                ('price', models.PositiveIntegerField(blank=True, db_index=True, verbose_name='Цена')),
            ],
        ),
    ]
